### ISSUE TITLE
Support Go 2 error

### ISSUE THREAD

**Issue by klimskripko** [airbrake/gobrake#103]
Proposal: https://golang.org/design/29934-error-values
This functionality expected to be in the standard library in Go 1.13
The [golang.org/x/xerrors](https://golang.org/x/xerrors) package provides Go 2 error implementation that can be used with earlier Go versions.

Go 2 errors contain stack frames, which can be extracted (as already done for pkg/errors https://github.com/airbrake/gobrake/pull/39)

**Comment by vmihailenco** [comment]
Looks like gobrake can't do much with xerrors, because there is no access to stack frames or a way to check if error contains a stack frame.
