### ISSUE TITLE
dynamic Timeout configuration for HTTP client

### ISSUE THREAD

**Issue by fertobar** [airbrake/gobrake#116]
hello,
there is a way to configure the timeout for the HTTP client?
https://github.com/airbrake/gobrake/blob/03c6c138e42246c054ff5c5f0a9e7ffbfba49703/notifier.go#L47

I would like to set eg in 2 seconds to reduce the probability of a bottle neck in a Sync notification in case service is not available

**Comment by vmihailenco** [comment]
Hi,

You should be able to provide `HTTPClient` in `NotifierOptions` - https://github.com/airbrake/gobrake/blob/03c6c138e42246c054ff5c5f0a9e7ffbfba49703/notifier.go#L78

**Comment by fertobar** [comment]
thanks @vmihailenco!
