### ISSUE TITLE
Gobrake Middleware Stacktrace only showing middleware

### ISSUE THREAD

**Issue by ahamidi** [airbrake/gobrake#12]
The way that stack tracing is currently implemented (using `runtime.Caller()`) isn't suitable for integration as Middleware.

Currently, since `runtime.Caller` only reports on the calling Goroutine, all you'll see is the stack trace for the middleware itself:

```
/Users/ahamidi/Dev/Go/src/github.com/codegangsta/negroni/negroni.go:24 in HandlerFunc.ServeHTTP
/Users/ahamidi/Dev/Go/src/github.com/codegangsta/negroni/negroni.go:33 in middleware.ServeHTTP
/Users/ahamidi/Dev/Go/src/github.com/codegangsta/negroni/negroni.go:73 in (*Negroni).ServeHTTP
/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1703 in serverHandler.ServeHTTP
/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1204 in (*conn).serve
/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 in goexit
```

In my case I've created a [Negroni](https://github.com/codegangsta/negroni) Middleware called [Airbraker](https://github.com/ahamidi/negroni-airbraker) that notifies Airbrake whenever it sees an error HTTP Status Code.

Any ideas on how I might be able to get it to report on other goroutines? (I've only found references to `runtime.Stack(buf, bool)`, which provides access stack traces for all running goroutines).

**Comment by vmihailenco** [comment]
I will try to write something meaningful using `runtime.FuncForPc`.

Internally we use https://github.com/airbrake/glog which reports important logs to Airbrake. Probably you will find it useful.

**Comment by ahamidi** [comment]
Ok great. Thanks for looking into that.

**Comment by vmihailenco** [comment]
@ahamidi here we go https://gist.github.com/vmihailenco/1fe2808e1a5b77180aaf. But please note that it relies heavily on `m.mux.Handler` to return func that handles the request. If you use different mux you will have to adopt your code. Or probably negroni can provide required API.

**Comment by ahamidi** [comment]
@vmihailenco brilliant, thanks!
