### ISSUE TITLE
`go get` hangs when running `go get gopkg.in/airbrake/gobrake.v1`

### ISSUE THREAD

**Issue by dmowcomber** [airbrake/gobrake#16]
`go get` hangs forever when running `go get gopkg.in/airbrake/gobrake.v1`

**Comment by vmihailenco** [comment]
I can't reproduce - probably it was temporal error. Can you try again?

**Comment by dmowcomber** [comment]
This was not a temporary issue for me. I was able to workaround this by manually cloning the repo into Godeps.
