### ISSUE TITLE
update to v4?

### ISSUE THREAD

**Issue by azumads** [airbrake/gobrake#17]

**Comment by vmihailenco** [comment]
Do you mean Airbrake v4 API? Then gobrake already uses latest API. Gobrake versions and Airbrake API versions don't match.

**Comment by azumads** [comment]
sorry, https://airbrake.io/docs/#error-notification-v3
Is this version?

**Comment by vmihailenco** [comment]
Yes, gobrake.v2 uses v3 Airbrake API - https://github.com/airbrake/gobrake/blob/master/notifier.go#L22

**Comment by azumads** [comment]
Thanks
