### ISSUE TITLE
Gobrake v5 is not respecting the HTTPClient

### ISSUE THREAD

**Issue by coder543** [airbrake/gobrake#176]
This line is not using the HTTPClient provided in the Notifier Options: https://github.com/airbrake/gobrake/blob/08fd4aef072cb2b7f7f1e29dc29be355de64022b/remote_config.go#L238

Which is causing gobrake to be upset in my application.

**Comment by jorenrc** [comment]
TLDR: As a result, proxy settings are not honored.

**Comment by coder543** [comment]
I'm also not sure under what conditions `gobrake` is attempting to write the `config.json` to disk, but the filesystem is read-only, so that just causes an extra layer of unhappiness

**Comment by coder543** [comment]
Thanks!
