### ISSUE TITLE
"go get" broken for Go 1.5 and below

### ISSUE THREAD

**Issue by stevvooe** [airbrake/gobrake#25]
https://github.com/airbrake/gobrake/commit/50cb9569931fc30e41f17689ffa36ea5e99896b7#diff-973a1a56d0cc9506ee822e801b41e635 references `http.StatusTooManyRequests`, which is defined in Go 1.6 and later. Builds that rely on Go 1.5 and earlier now fail.

https://github.com/Sirupsen/logrus/issues/445 describes an example of that failure.

I'm not sure what compatibility guarantee is for airbrake, but `logrus` is supporting back all the way to Go 1.3. It would be good to get an idea about where airbrake stands there and we can make a decision for logrus.

**Comment by vmihailenco** [comment]
We don't have a strict policy, but in general we aim support 2 latest Go versions - 1.6 & 1.7. But if the problem is only with `http.StatusTooManyRequests` and it causes too many troubles for logrus we can remove `http.StatusTooManyRequests` usage.

**Comment by stevvooe** [comment]
Looks like this is only referenced through the example in https://github.com/Sirupsen/logrus/blob/master/examples/hook/hook.go#L5. Perhaps, we could use another example besides airbrake for hooks.

**Comment by vmihailenco** [comment]
I fixed this by changing gobrake v2.0.9 to work with Go 1.4 - 1.7. Hope it helps.

**Comment by stevvooe** [comment]
@vmihailenco Thanks! Looks like builds are working again.
