### ISSUE TITLE
Auto-notify when logging at the error level

### ISSUE THREAD

**Issue by dsuare1** [airbrake/gobrake#294]
I'm using the [zap](https://github.com/uber-go/zap) logging library and have recently added airbrake to the project.

I followed the quick example and configured my airbrake notifier with the correct project id and key, then manually called `airbrake.Notify(...)` and saw the error reported in my project. So I can confirm that the connection is working as expected.

My issue is that I don't want to have to go through my entire codebase and insert manual calls to `airbrake.Notify(...)` where relevant, but would rather configure airbrake to do so every time something is logged at the `error` level.

Is there a way to do this?

**Comment by chimanjain** [comment]
Hi @dsuare1, currently we don't have an integration with [zap](https://github.com/uber-go/zap) logging library, but we have put this in our to do list to support [zap](https://github.com/uber-go/zap) logging library.

**Comment by dsuare1** [comment]
Thanks @chimanjain - I was able to achieve what I wanted using [zap's hooks](https://github.com/uber-go/zap/blob/ee349f9e2995499f66628dc573382939b6941b09/options.go#L48). Only issue was that I had to refactor the initialization of my logger to take in the *gobrake.Notifier.

**Comment by chimanjain** [comment]
Hi @dsuare1, I started working on [zap](https://github.com/uber-go/zap) integration with gobrake and I found an issue with [zap's hooks](https://github.com/uber-go/zap/blob/ee349f9e2995499f66628dc573382939b6941b09/options.go#L48) that it doesn't capture **[]zapcore.Field**. So I created a [zap](https://github.com/uber-go/zap) Core in #299 which sends the [zap](https://github.com/uber-go/zap) logs to airbrake.
