### ISSUE TITLE
Custom stacktrace

### ISSUE THREAD

**Issue by marczahn** [airbrake/gobrake#30]
Hi,

related to this: https://github.com/airbrake/gobrake/issues/12 I would like to "inject" a custom stacktrace. My case (I think it is pretty common) is that I want to have one place where I call the logger. But since the stacktrace generation is hard wired in the go library it is impossible to use a custom one which is different from the place the logger is called.

**Comment by vmihailenco** [comment]
Hi,

You can use `gobrake.NewNotice` to omit some backtrace record (`depth` argument) or set your own backtrace - https://godoc.org/gopkg.in/airbrake/gobrake.v2#NewNotice. See how this is used in glog - https://github.com/airbrake/glog/blob/master/airbrake.go#L61-L64
