### ISSUE TITLE
Airbrake on low internet connectivity

### ISSUE THREAD

**Issue by meetme2meat** [airbrake/gobrake#326]
Before even I start, having used airbrake in past gives me the impression things I'm looking for perhaps do not exist yet in airbrake. But I just want to double-check. 

We have our system deployed at remote places where internet connectivity is not stable. We would love to have error monitoring capability like airbrake in our system but we are not sure what would happen in an event(error event on airbrake) if the internet at the remote system is currently down. Will it drop the error(I'm assuming, it does)? Also is there a provision to send those errors to the airbrake system when the internet is up on the system?

**Comment by kyrylo** [comment]
Hey, Viren! In gobrake v5.6.0 we've actually released a feature called "backlog". I am not sure why it's not mentioned in the CHANGELOG (@chimanjain could you please add a mention?).

This somewhat helps in your scenario. If the airbrake server is unreachable, the error you are trying to send (or an APM event) would be cached and attempted to send later. I don't see any documentation on how to use it, though (@chimanjain, again, could you please work on that?).

**Comment by chimanjain** [comment]
Yes, there is a provision for that, we provide a backlog retry mechanism which retries to send the errors and monitoring stats to Airbrake after some time. To read more, please check the documentation [here](https://docs.airbrake.io/docs/platforms/go-lang/#disablebacklog) and in [FAQ](https://docs.airbrake.io/docs/faq/how-can-avoid-losing-performance-error).
