### ISSUE TITLE
Extract stacktraces from errors of pkg/errors

### ISSUE THREAD

**Issue by ihrwein** [airbrake/gobrake#37]
Thanks for making this great library.

I am transitioning some code to use  [pkg/errors](https://github.com/pkg/errors) for error logging. This package captures the stacktraces of the place where the errors are created. Those stacktraces are more precise than the ones collected by gobrake, since the error creation and its logging can be far away (I use sirupsen/logrus's log.Errorln(err)).

Before I send a PR I'd like to ask your opinion about this feature. Would you merge a PR that implements it? I've one ready.

**Comment by vmihailenco** [comment]
Absolutely, we are definitely interested in supporting pkg/errors.

**Comment by ihrwein** [comment]
Thanks, let's see what the maintainers of `pkg/errors` think about it.

**Comment by vmihailenco** [comment]
I don't have experience with pkg/errors, but it looks like you need https://godoc.org/github.com/pkg/errors#ex-package--StackTrace

**Comment by ihrwein** [comment]
You are right, the only problem that `StackTrace` is not implemented for the errors created by `errors.Wrap*()`. That function returns a `*withStack` and that's the type that reaches `gobrake` through logrus (`log.WithError(err).Errorln(err)`). This is the problem that I want to address in https://github.com/pkg/errors/issues/132

**Comment by ihrwein** [comment]
I've opened https://github.com/airbrake/gobrake/pull/39 so you can see the initial implementation.

**Comment by puellanivis** [comment]
As mentioned from the pkg/errors issue, it doesn’t seem like any change need be made to pkg.errors as of your last checkin…

A program that just does `gobrake.NewNotice(errors.Wrap(os.ErrNotExist, "foo"), nil, 0)` then prints the JSON of the backtrace embedded within shows the following:

```
[
  {
    "file": "stacktrace.go",
    "line": 19,
    "function": "main"
  },
  {
    "file": "proc.go",
    "line": 185,
    "function": "main"
  },
  {
    "file": "asm_amd64.s",
    "line": 2337,
    "function": "goexit"
  }
]
```

While the standard vanilla errors.New() shows:

```
[
  {
    "file": "${GOPATH}/src/github.com/ihrwein/gobrake/util.go",
    "line": 25,
    "function": "stack"
  },
  {
    "file": "${GOPATH}/src/github.com/ihrwein/gobrake/util.go",
    "line": 79,
    "function": "getStack"
  },
  {
    "file": "${GOPATH}/src/github.com/ihrwein/gobrake/notice.go",
    "line": 72,
    "function": "NewNotice"
  },
  {
    "file": "stacktrace.go",
    "line": 19,
    "function": "main"
  },
  {
    "file": "/usr/local/go/src/runtime/proc.go",
    "line": 185,
    "function": "main"
  },
  {
    "file": "/usr/local/go/src/runtime/asm_amd64.s",
    "line": 2337,
    "function": "goexit"
  }
]
```

**Comment by ihrwein** [comment]
@puellanivis You are right, probably I had some environment issues.

I added a unit test to my PR in this repo.
