### ISSUE TITLE
Cert Error 

### ISSUE THREAD

**Issue by rbg** [airbrake/gobrake#379]
gobrake: 2023/10/19 00:07:06 remote_config.go:82: fetchConfig failed for https://notifier-configs.airbrake.io/2020-06-18/config/*/config.json. Reason: Get "https://notifier-configs.airbrake.io/2020-06-18/config/*/config.json?language=go1.21.0&notifier_name=gobrake&notifier_version=5.6.1&os=linux": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2023-10-19T00:07:06Z is after 2023-10-18T21:27:43Z

**Comment by Brandon21318** [comment]
We have found and addressed the issue. Thank you for bringing this to our attention Robert.
