### ISSUE TITLE
At time airbrake is not logging the error.. 

### ISSUE THREAD

**Issue by meetme2meat** [airbrake/gobrake#94]
I'm not sure what is the cause of this but we are seeing at times that gobrake does not report the error reported by the system.

This is something I have personally noticed when was tailing the live log of the production and saw the statement written to the log file but the airbrake code that supposes to write the error to airbrake did not log any error.

If code helps here how we call airbrake [in our code](https://gist.github.com/meetme2meat/0f66971e988ee8675f3af25aac4b52b8#file-airbrake-go). 

 Also, what is expected behaviour in gobrake when network error happens.

**Comment by oliver-hohn** [comment]
@meetme2meat have you received any updates on why the error is sometimes not logged? I'm seeing a similar issue when using `gobrake` and `net/http`, where "unrecovered" panics are not being sent to Airbrake even though in the stack-trace I can see `gobrake.NotifyOnPanic` has been called.

For reference, I'm using `gobrake v3.7.4`.

**Comment by phumpal** [comment]
@oliver-hohn can you send a note about this issue along with the `ProjectId` to support@airbrake.io? I'd like to do some digging on our end as well. Thanks!

**Comment by oliver-hohn** [comment]
@phumpal I've found the root cause of my issue after adding logging when `SendNotice` fails (https://github.com/airbrake/gobrake/pull/119). `gobrake` was being closed too early so the `SendNotice` call was a no-op.

**Comment by kyrylo** [comment]
Solved by https://github.com/airbrake/gobrake/pull/133.
